version: "3.8"
services:
    db:
        image: postgres:15.1-alpine
        container_name: db_app
        volumes:
            - pgdata:/var/lib/postgresql/data
        command: -p 1221
        expose:
            - 1221
        ports:
            - "1221:5432"
        env_file:
            - .env-prod
        networks:
            - ylab-network
    app:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env-prod
        container_name: fastapi_app
        command: ["/fastapi_app/docker/app.sh"]
        volumes:
            - /app/generated_files
        networks:
            - ylab-network
        ports:
            - 8000:8000
        depends_on:
            - db
        restart: always

networks:
    ylab-network:
        name: ylab-network
volumes:
    pgdata:
