"""Cascade

Revision ID: 70bc7ae6d931
Revises: 71646d800542
Create Date: 2024-01-20 01:50:57.890456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70bc7ae6d931'
down_revision: Union[str, None] = '71646d800542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dish_submenu_id_fkey', 'dish', type_='foreignkey')
    op.create_foreign_key(None, 'dish', 'submenu', ['submenu_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('submenu_menu_id_fkey', 'submenu', type_='foreignkey')
    op.create_foreign_key(None, 'submenu', 'menu', ['menu_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submenu', type_='foreignkey')
    op.create_foreign_key('submenu_menu_id_fkey', 'submenu', 'menu', ['menu_id'], ['id'])
    op.drop_constraint(None, 'dish', type_='foreignkey')
    op.create_foreign_key('dish_submenu_id_fkey', 'dish', 'submenu', ['submenu_id'], ['id'])
    # ### end Alembic commands ###
